# porta que a aplicação do fornecedor vai subir
server:
  port: 8081

#contexto anterior do spring que o ja levantado pela app : bootstrap
# utilizar as configuracao do bootstrap.yml p/ o hibernata buscar as cfg do bd

    
# registrar no eureka   
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka    
 