# porta que a aplicação do fornecedor vai subir
server:
  port: 8081

# configurações do bd nao sao mais necessárias aqui pois agora o fornecedor vai acessar o spring config server
spring:
  application:
    name: 'fornecedor'    


    
# registrar no eureka   
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka    
 