server:
  port: 8888
  
spring:
  profiles:
    active: native # busca as cfg dentro do file system da maquina q tรก rodadno o ms
  cloud:
    config:
      server:
        native:
          search-locations:  c:/microservice-repo #pasta aonde estao as cfg
