server:
  port: 8888


  
spring:
  cloud:
    config:
      server:
        git:         # Migrando do file system local para o GitHub
          uri: https://github.com/j19791/microservice-repo/
          search-paths:  fornecedor
